<a href="https://colab.research.google.com/github/Tharunkumar1724/Bank-transactions/blob/main/models_used_for_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
path="/content/gdrive/My Drive/ Dataset/fraud_details_cleaned.csv"

Mounted at /content/gdrive


In [ ]:
mat=pd.read_csv(path)
df=pd.DataFrame(mat)

In [ ]:
df.head()

SERVICE_NO  FRAUD_NUMBER        Date  \
0   201995931      496808.0  2020-02-13   
1   200872755      224397.0  2011-12-15   
2   200264239      200867.0  2011-04-25   
3   200062554      389751.0  2016-06-09   
4   200318029      398508.0  2016-11-23   

                                          FRAUD_TYPE  \
0                   DIRECT CONNECTION ON SUPPLY WIRE   
1             SHUNT ON CURRENT WINDING IN THE METER    
2             SHUNT ON CURRENT WINDING IN THE METER    
3  GAP OF ATTACK WHEEL COMPARE TO THE UNLIMITED S...   
4                 DIRECT CONNECTION ON BURRIED CABLE   

                                        OBSERVATIONS REFERENCE_DIRECTION  \
0  PIQUAGE SUR LE RESEAU D'ALIMENTATION A L'AIDE ...             EKOUNOU   
1                             SHUNT BOBINE INTENSITE          OYOM ABANG   
2                                                          TUNEL LOGBABA   
3    DEUX BOBINES FLUX DECONNECTEES DANS LE COMPTEUR        QT BONAPRISO   
4  MINUTERIE 5/15 JAUNE DANS LE CPT 10/60A AVEC S...         QT BONABERI   

   TOTAL_RECOVERED_AMOUNT  RECORD_NUMBER                           STATUS  \
0                112105.0    435204984.0  PAID UNDER INSTALMENT AGREEMENT   
1                475486.0    241419588.0  PAID UNDER INSTALMENT AGREEMENT   
2                511261.0    221271745.0  PAID UNDER INSTALMENT AGREEMENT   
3                641597.0    332281283.0                             PAID   
4               1841235.0    343215232.0              POTENTIAL WRITE-OFF   

                  APPLIANCE_CODE   POWER  QUANTITY  HOURS_OF_USE_PER_DAY  
0                       COMPUTER   200.0       1.0                   8.0  
1  TELEVISEUR/VACUUM CLEANER/FAX   100.0       3.0                  10.0  
2              REFRIGERATOR 250L   190.0       1.0                  14.0  
3                   FREEZER 375L   160.0       2.0                  14.0  
4                  ELECTRIC IRON  1000.0       1.0                   2.0

In [ ]:
# Rename columns to meaningful names
df.columns = [
                    # Unnamed: 0
    'customer_number',         # NIS_RAD
    'fraud_case_number',       # NUM_FR
    'detection_date',          # F_DETEC
    'fraud_type',              # TIPO(TR.TIP_FRA)
    'fraud_observation',       # OBS_FRA
    'address_reference',       # REF_DIR
    'total_recovered_amount',  # IMP_TOT_REC
    'recovery_number',         # NUM_REC
    'account_status',          # ESTADO(RE.EST_ACT)
    'device_code',             # CODIGO(AP.CO_APARATO)
    'power_capacity_kw',       # POTENCIA
    'quantity',                # CANTIDAD
    'daily_usage_hours'        # HORAS_USO_DIA
]


print(df.head())

   customer_number  fraud_case_number detection_date  \
0        201995931           496808.0     2020-02-13   
1        200872755           224397.0     2011-12-15   
2        200264239           200867.0     2011-04-25   
3        200062554           389751.0     2016-06-09   
4        200318029           398508.0     2016-11-23   

                                          fraud_type  \
0                   DIRECT CONNECTION ON SUPPLY WIRE   
1             SHUNT ON CURRENT WINDING IN THE METER    
2             SHUNT ON CURRENT WINDING IN THE METER    
3  GAP OF ATTACK WHEEL COMPARE TO THE UNLIMITED S...   
4                 DIRECT CONNECTION ON BURRIED CABLE   

                                   fraud_observation address_reference  \
0  PIQUAGE SUR LE RESEAU D'ALIMENTATION A L'AIDE ...           EKOUNOU   
1                             SHUNT BOBINE INTENSITE        OYOM ABANG   
2                                                        TUNEL LOGBABA   
3    DEUX BOBINES FLUX DECONNE

In [ ]:
df.loc[0]

customer_number                                                   201995931
fraud_case_number                                                  496808.0
detection_date                                                   2020-02-13
fraud_type                                 DIRECT CONNECTION ON SUPPLY WIRE
fraud_observation         PIQUAGE SUR LE RESEAU D'ALIMENTATION A L'AIDE ...
address_reference                                                   EKOUNOU
total_recovered_amount                                             112105.0
recovery_number                                                 435204984.0
account_status                              PAID UNDER INSTALMENT AGREEMENT
device_code                                                        COMPUTER
power_capacity_kw                                                     200.0
quantity                                                                1.0
daily_usage_hours                                                       8.0
Name: 0, dtype: object

In [ ]:
df.account_status.value_counts()

account_status
POTENTIAL WRITE-OFF                             37860
PAID UNDER INSTALMENT AGREEMENT                 36289
PAID                                            32978
CANCELLED                                       11210
SUSPENDED                                        6633
SENT TO CUSTOMER                                 1692
UNDER INSTALMENT AGREEMENT                        920
BILLED                                            467
MANUAL DEFINITE WRITE-OFF                         395
FINAL DEMAND LETTER                               105
CANCELLED DUE TO TRANSFER TO ANOTHER ACCOUNT       71
SUSPENSION PROCESS DETAINED                        56
AUTOMATICALLY COLLECTED STAFF INVOICE              20
AUTOMATICALLY COLLECTED ZERO AMOUNT                 4
MANUAL POTENTIAL WRITE-OFF                          2
Name: count, dtype: int64

In [ ]:
fraud_statuses = [
    'POTENTIAL WRITE-OFF',
    'MANUAL DEFINITE WRITE-OFF',
    'MANUAL POTENTIAL WRITE-OFF',
    'SUSPENDED',
    'SUSPENSION PROCESS DETAINED',
    'FINAL DEMAND LETTER',
    'CANCELLED',
    'CANCELLED DUE TO TRANSFER TO ANOTHER ACCOUNT'
]

df['is_fraud'] = df['account_status'].apply(lambda x: 1 if x in fraud_statuses else 0)

In [ ]:
from sklearn.preprocessing import LabelEncoder

# List of columns to encode
categorical_cols = ['fraud_type', 'fraud_observation', 'address_reference',
                    'account_status', 'device_code']

# Initialize the encoder
le = LabelEncoder()

# Apply label encoding to each categorical column
for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))

# Now your DataFrame has label-encoded values in those columns
print(df.head())

   customer_number  fraud_case_number detection_date  fraud_type  \
0        201995931           496808.0     2020-02-13          19   
1        200872755           224397.0     2011-12-15          44   
2        200264239           200867.0     2011-04-25          44   
3        200062554           389751.0     2016-06-09          24   
4        200318029           398508.0     2016-11-23          15   

   fraud_observation  address_reference  total_recovered_amount  \
0              10904              12305                112105.0   
1              15044              21170                475486.0   
2                  0              25000                511261.0   
3               4688              22376                641597.0   
4               6726              22322               1841235.0   

   recovery_number  account_status  device_code  power_capacity_kw  quantity  \
0      435204984.0               9           29              200.0       1.0   
1      241419588.0          

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd



In [ ]:
scaler = StandardScaler()

# Scale all features except customer number
scaled_features = scaler.fit_transform(df.drop(['customer_number','is_fraud','detection_date'], axis=1))

In [ ]:
df['total_power'] = df['device_code'] * df['power_capacity_kw'] * df['quantity']

In [ ]:
df.loc[0]

customer_number             201995931
fraud_case_number            496808.0
detection_date             2020-02-13
fraud_type                         19
fraud_observation               10904
address_reference               12305
total_recovered_amount       112105.0
recovery_number           435204984.0
account_status                      9
device_code                        29
power_capacity_kw               200.0
quantity                          1.0
daily_usage_hours                 8.0
is_fraud                            0
total_power                    5800.0
Name: 0, dtype: object

In [ ]:
df.drop(['device_code', 'power_capacity_kw', 'quantity'], axis=1, inplace=True)

print(df)

        customer_number  fraud_case_number detection_date  fraud_type  \
0             201995931           496808.0     2020-02-13          19   
1             200872755           224397.0     2011-12-15          44   
2             200264239           200867.0     2011-04-25          44   
3             200062554           389751.0     2016-06-09          24   
4             200318029           398508.0     2016-11-23          15   
...                 ...                ...            ...         ...   
128697        200724854           393395.0     2016-08-03          19   
128698        202002652           398533.0     2016-11-24          27   
128699        200269398           463135.0     2019-09-19          47   
128700        201004711           217446.0     2011-10-10           4   
128701        201631766           410580.0     2017-06-17           4   

        fraud_observation  address_reference  total_recovered_amount  \
0                   10904              12305       

In [ ]:
df['totalfraud']=df['fraud_type']+df['fraud_observation']

In [ ]:
df.drop(['fraud_type', 'fraud_observation'], axis=1, inplace=True)

print(df)

        customer_number  fraud_case_number detection_date  address_reference  \
0             201995931           496808.0     2020-02-13              12305   
1             200872755           224397.0     2011-12-15              21170   
2             200264239           200867.0     2011-04-25              25000   
3             200062554           389751.0     2016-06-09              22376   
4             200318029           398508.0     2016-11-23              22322   
...                 ...                ...            ...                ...   
128697        200724854           393395.0     2016-08-03               8642   
128698        202002652           398533.0     2016-11-24              13155   
128699        200269398           463135.0     2019-09-19              22467   
128700        201004711           217446.0     2011-10-10               5488   
128701        201631766           410580.0     2017-06-17               1149   

        total_recovered_amount  recover

In [ ]:
df.head()


customer_number  fraud_case_number detection_date  address_reference  \
0        201995931           496808.0     2020-02-13              12305   
1        200872755           224397.0     2011-12-15              21170   
2        200264239           200867.0     2011-04-25              25000   
3        200062554           389751.0     2016-06-09              22376   
4        200318029           398508.0     2016-11-23              22322   

   total_recovered_amount  recovery_number  account_status  daily_usage_hours  \
0                112105.0      435204984.0               9                8.0   
1                475486.0      241419588.0               9               10.0   
2                511261.0      221271745.0               9               14.0   
3                641597.0      332281283.0               8               14.0   
4               1841235.0      343215232.0              10                2.0   

   is_fraud  total_power  totalfraud  
0         0       5800.0       10923  
1         0      35400.0       15088  
2         0      19760.0          44  
3         0      16000.0        4712  
4         1      40000.0        6741

In [ ]:
df['estimated_daily_energy_consumption'] = df['daily_usage_hours'] * df['total_power']
df.drop(['daily_usage_hours', 'total_power'], axis=1, inplace=True)
print(df.head())

   customer_number  fraud_case_number detection_date  address_reference  \
0        201995931           496808.0     2020-02-13              12305   
1        200872755           224397.0     2011-12-15              21170   
2        200264239           200867.0     2011-04-25              25000   
3        200062554           389751.0     2016-06-09              22376   
4        200318029           398508.0     2016-11-23              22322   

   total_recovered_amount  recovery_number  account_status  is_fraud  \
0                112105.0      435204984.0               9         0   
1                475486.0      241419588.0               9         0   
2                511261.0      221271745.0               9         0   
3                641597.0      332281283.0               8         0   
4               1841235.0      343215232.0              10         1   

   totalfraud  estimated_daily_energy_consumption  
0       10923                             46400.0  
1       1508

In [ ]:
df.head()

customer_number  fraud_case_number detection_date  address_reference  \
0        201995931           496808.0     2020-02-13              12305   
1        200872755           224397.0     2011-12-15              21170   
2        200264239           200867.0     2011-04-25              25000   
3        200062554           389751.0     2016-06-09              22376   
4        200318029           398508.0     2016-11-23              22322   

   total_recovered_amount  recovery_number  account_status  is_fraud  \
0                112105.0      435204984.0               9         0   
1                475486.0      241419588.0               9         0   
2                511261.0      221271745.0               9         0   
3                641597.0      332281283.0               8         0   
4               1841235.0      343215232.0              10         1   

   totalfraud  estimated_daily_energy_consumption  
0       10923                             46400.0  
1       15088                            354000.0  
2          44                            276640.0  
3        4712                            224000.0  
4        6741                             80000.0

In [ ]:
path1="/content/gdrive/My Drive/ Dataset/validation_data.csv"

In [ ]:
df1=pd.read_csv(path1)

In [ ]:
df['customer_number'] = df['customer_number'].astype(str).str.replace(r'[^0-9]', '', regex=True)
df['customer_number'] = df['customer_number'].astype('float64').astype('int64')
df3=pd.merge(df,df1,left_on='customer_number', right_on='SERVICE_NBR', how='inner')

In [ ]:
df3.loc[0]

customer_number                         200872755
fraud_case_number                        224397.0
detection_date                         2011-12-15
address_reference                           21170
total_recovered_amount                   475486.0
recovery_number                       241419588.0
account_status                                  9
is_fraud                                        0
totalfraud                                  15088
estimated_daily_energy_consumption       354000.0
PHASE                                      230219
TARIFF                                     165194
POWER_SUSCRIBED                         -0.332808
TENSION                                    230514
DIVISION                                    18100
ACTIVITY_CMS                               220294
REGION                                      91875
AGENCY                                       4833
payment_mode                               121960
IsActive                                        1
Tenure_Days                              1.838453
Avg_Consumption                         -0.002804
Max_Consumption                         -0.002566
Total_Payment                           -0.168012
Spike_Count                             -0.718519
Has_inspected                                   1
inspection_count                                1
fraud_found_category                            1
Found_fraud                                     1
SERVICE_NBR                             200872755
Name: 0, dtype: object

In [ ]:
import pandas as pd
import numpy as np

# Sample — assuming df is your DataFrame
# Target: 'Found_fraud'

# Convert 'detection_date' to datetime and then to ordinal
df3['detection_date'] = pd.to_datetime(df3['detection_date'], errors='coerce').apply(lambda x: x.toordinal() if pd.notna(x) else -1)

# Convert 'recovery_number' to numeric, coercing errors
df3['recovery_number'] = pd.to_numeric(df3['recovery_number'], errors='coerce')

# Impute NaN values in 'estimated_daily_energy_consumption' with the mean
df3['estimated_daily_energy_consumption'].fillna(df3['estimated_daily_energy_consumption'].mean(), inplace=True)


X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Convert to numpy
X = X.values
y = y.values

In [ ]:
# Reshape (samples, time_steps, features)
X = X.reshape((X.shape[0], X.shape[1], 1))

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features (important for RNNs)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Reshape (samples, time_steps, features) AFTER scaling
X_train_reshaped = X_train_scaled.reshape((X_train_scaled.shape[0], X_train_scaled.shape[1], 1))
X_test_reshaped = X_test_scaled.reshape((X_test_scaled.shape[0], X_test_scaled.shape[1], 1))

# Print the shape to verify the number of features
print("Shape of X_train_reshaped:", X_train_reshaped.shape)


# Define RNN model
model = Sequential()
model.add(SimpleRNN(64, input_shape=(X_train_reshaped.shape[1], 1), activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # binary classification

# Compile model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fit model
history = model.fit(X_train_reshaped, y_train, epochs=20, batch_size=16, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

Shape of X_train_reshaped: (9180, 29, 1)
Epoch 1/20
459/459 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9853 - loss: 1.6376 - val_accuracy: 0.9973 - val_loss: 0.0223
Epoch 2/20
459/459 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9986 - loss: 0.0091 - val_accuracy: 1.0000 - val_loss: 0.0011
Epoch 3/20
459/459 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9999 - loss: 6.6365e-04 - val_accuracy: 1.0000 - val_loss: 1.6305e-04
Epoch 4/20
459/459 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 1.0000 - loss: 1.2422e-04 - val_accuracy: 1.0000 - val_loss: 8.9746e-05
Epoch 5/20
459/459 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 1.0000 - loss: 6.3098e-05 - val_accuracy: 1.0000 - val_loss: 6.6891e-05
Epoch 6/20
459/459 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 1.0000 - loss: 4.2762e-05 - val_accuracy: 1.0000 - val_loss: 2.8429e-05
Epoch 7/20
459/459 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 1.0000 - loss: 2.1882e-05 - val_accuracy: 1.0000 - val_loss: 2.1083e-05
Epoch 8/20
459/459 ━━━

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
import pandas as pd

# Example: assuming df is your full DataFrame, including 'Found_fraud'
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Scale features (very important for ANN)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build ANN model
model = Sequential()
model.add(Dense(128, input_shape=(X_train_scaled.shape[1],), activation='relu'))
model.add(Dropout(0.3))   # dropout to prevent overfitting
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # binary output

# Compile model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train model
history = model.fit(X_train_scaled, y_train, epochs=30, batch_size=32, validation_split=0.2)

# Evaluate model
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"\nTest Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

# Predict
y_pred_prob = model.predict(X_test_scaled)
y_pred = (y_pred_prob > 0.5).astype(int)

# Metrics
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Epoch 1/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9545 - loss: 0.1732 - val_accuracy: 0.9978 - val_loss: 0.0141
Epoch 2/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9990 - loss: 0.0109 - val_accuracy: 0.9984 - val_loss: 0.0040
Epoch 3/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9995 - loss: 0.0034 - val_accuracy: 1.0000 - val_loss: 6.9547e-04
Epoch 4/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 1.0000 - val_loss: 1.4566e-04
Epoch 5/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9999 - loss: 4.7497e-04 - val_accuracy: 1.0000 - val_loss: 7.6166e-05
Epoch 6/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 1.0000 - loss: 6.3840e-04 - val_accuracy: 1.0000 - val_loss: 1.0622e-05
Epoch 7/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9999 - loss: 3.6218e-04 - val_accuracy: 1.0000 - val_loss: 2.0938e-05
Epoch 8/30
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9999 -

In [ ]:
unique, counts = np.unique(y, return_counts=True)
print(dict(zip(unique, counts)))


{np.int64(0): np.int64(48), np.int64(1): np.int64(11427)}


In [ ]:
print(df3.dtypes)

customer_number                         int64
fraud_case_number                     float64
detection_date                          int64
address_reference                       int64
total_recovered_amount                float64
recovery_number                       float64
account_status                          int64
is_fraud                                int64
totalfraud                              int64
estimated_daily_energy_consumption    float64
PHASE                                   int64
TARIFF                                  int64
POWER_SUSCRIBED                       float64
TENSION                                 int64
DIVISION                                int64
ACTIVITY_CMS                            int64
REGION                                  int64
AGENCY                                  int64
payment_mode                            int64
IsActive                                int64
Tenure_Days                           float64
Avg_Consumption                   

In [ ]:
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import numpy as np
import pandas as pd


In [ ]:
# Split features and labels
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Split into train-test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Scale features (Isolation Forest benefits from scaling)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [ ]:
# Fit Isolation Forest — set contamination based on expected anomaly ratio
iso_forest = IsolationForest(
    contamination=0.002,  # 0.2% anomalies (tune this based on your fraud rate)
    random_state=42
)

iso_forest.fit(X_train_scaled)


IsolationForest(contamination=0.002, random_state=42)

In [ ]:
# Predict on test set (-1 = anomaly, 1 = normal)
predictions = iso_forest.predict(X_test_scaled)

# Convert to 0 (non-fraud) and 1 (fraud)
fraud_pred = np.where(predictions == -1, 1, 0)


In [ ]:
# Confusion Matrix and Classification Report
print("Confusion Matrix:")
print(confusion_matrix(y_test, fraud_pred))

print("\nClassification Report:")
print(classification_report(y_test, fraud_pred))

# ROC AUC Score (if your y_test has labels)
print("\nROC AUC Score:")
print(roc_auc_score(y_test, fraud_pred))


Confusion Matrix:
[[  10    0]
 [2282    3]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      1.00      0.01        10
           1       1.00      0.00      0.00      2285

    accuracy                           0.01      2295
   macro avg       0.50      0.50      0.01      2295
weighted avg       1.00      0.01      0.00      2295


ROC AUC Score:
0.5006564551422319


In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import numpy as np
import pandas as pd


In [ ]:
# Features and labels
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Scale
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train only on class 0 (normal) samples
X_train_norm = X_train_scaled[y_train == 0]


In [ ]:
input_dim = X_train_norm.shape[1]

# Define Autoencoder
input_layer = Input(shape=(input_dim,))
encoded = Dense(16, activation='relu')(input_layer)
encoded = Dense(8, activation='relu')(encoded)
encoded = Dense(4, activation='relu')(encoded)

decoded = Dense(8, activation='relu')(encoded)
decoded = Dense(16, activation='relu')(decoded)
output_layer = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=output_layer)

# Compile
autoencoder.compile(optimizer='adam', loss='mse')


In [ ]:
history = autoencoder.fit(
    X_train_norm, X_train_norm,
    epochs=50, batch_size=32,
    validation_split=0.1, verbose=1
)


Epoch 1/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 322ms/step - loss: 20.3664 - val_loss: 17.1091
Epoch 2/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 20.1279 - val_loss: 17.0200
Epoch 3/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 20.1844 - val_loss: 16.9364
Epoch 4/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 20.2444 - val_loss: 16.8593
Epoch 5/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 20.1443 - val_loss: 16.7956
Epoch 6/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 19.7482 - val_loss: 16.7391
Epoch 7/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 19.7404 - val_loss: 16.6886
Epoch 8/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 19.8313 - val_loss: 16.6350
Epoch 9/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 20.0622 - val_loss: 16.5947
Epoch 10/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 20.0290 - val_loss: 16.5618
Epoch 11/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 20.0131 - val_loss: 16.5402
Epoch 12/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 

In [ ]:
# Get reconstruction error for test set
X_test_pred = autoencoder.predict(X_test_scaled)
mse = np.mean(np.power(X_test_scaled - X_test_pred, 2), axis=1)


72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [ ]:
threshold = np.percentile(mse, 95)
print(f"Reconstruction error threshold: {threshold:.6f}")


Reconstruction error threshold: 1.870304


In [ ]:
fraud_pred = (mse > threshold).astype(int)


In [ ]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, fraud_pred))

print("\nClassification Report:")
print(classification_report(y_test, fraud_pred))

print("\nROC AUC Score:")
print(roc_auc_score(y_test, mse))

Confusion Matrix:
[[   0   10]
 [2180  105]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.91      0.05      0.09      2285

    accuracy                           0.05      2295
   macro avg       0.46      0.02      0.04      2295
weighted avg       0.91      0.05      0.09      2295


ROC AUC Score:
0.0027571115973741792


In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import numpy as np
import pandas as pd


In [ ]:
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [ ]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

all_preds = []
all_true = []
all_errors = []

for train_index, test_index in kf.split(X_scaled):
    X_train_cv, X_test_cv = X_scaled[train_index], X_scaled[test_index]
    y_train_cv, y_test_cv = y.iloc[train_index], y.iloc[test_index]

    # Optional: train on only class 0 normal samples
    X_train_norm = X_train_cv[y_train_cv == 0]

    # Autoencoder model
    input_dim = X_train_norm.shape[1]
    input_layer = Input(shape=(input_dim,))
    encoded = Dense(16, activation='relu')(input_layer)
    encoded = Dense(8, activation='relu')(encoded)
    encoded = Dense(4, activation='relu')(encoded)
    decoded = Dense(8, activation='relu')(encoded)
    decoded = Dense(16, activation='relu')(decoded)
    output_layer = Dense(input_dim, activation='linear')(decoded)

    autoencoder = Model(inputs=input_layer, outputs=output_layer)
    autoencoder.compile(optimizer='adam', loss='mse')

    # Train
    autoencoder.fit(X_train_norm, X_train_norm,
                    epochs=30, batch_size=32,
                    verbose=0)

    # Reconstruction error on test set
    X_test_pred = autoencoder.predict(X_test_cv)
    mse = np.mean(np.power(X_test_cv - X_test_pred, 2), axis=1)

    # Use 95th percentile threshold of training reconstruction error
    train_recon = autoencoder.predict(X_train_norm)
    train_mse = np.mean(np.power(X_train_norm - train_recon, 2), axis=1)
    threshold = np.percentile(train_mse, 95)

    preds = (mse > threshold).astype(int)

    # Collect results
    all_preds.extend(preds)
    all_true.extend(y_test_cv)
    all_errors.extend(mse)


72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


In [ ]:
print("Confusion Matrix:")
print(confusion_matrix(all_true, all_preds))

print("\nClassification Report:")
print(classification_report(all_true, all_preds))

print("\nROC AUC Score:")
print(roc_auc_score(all_true, all_errors))


Confusion Matrix:
[[   46     2]
 [11421     6]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.96      0.01        48
           1       0.75      0.00      0.00     11427

    accuracy                           0.00     11475
   macro avg       0.38      0.48      0.00     11475
weighted avg       0.75      0.00      0.00     11475


ROC AUC Score:
0.0026454158280096846


In [ ]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import pandas as pd
import numpy as np

In [ ]:
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [ ]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X_scaled)

# Cluster labels
clusters = kmeans.labels_


In [ ]:
# Map cluster labels to actual labels for comparison
cluster_mapping = pd.crosstab(clusters, y)
print(cluster_mapping)

# Choose cluster with fewer class 0 samples as fraud cluster
fraud_cluster = cluster_mapping[0].idxmin()

# Predict labels: 1 if in fraud cluster else 0
y_pred = np.where(clusters == fraud_cluster, 1, 0)


Found_fraud   0     1
row_0                
0            21  7397
1            27  4030


In [ ]:
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))

print("\nClassification Report:")
print(classification_report(y, y_pred))

print("\nROC AUC Score:")
print(roc_auc_score(y, y_pred))


Confusion Matrix:
[[  27   21]
 [4030 7397]]

Classification Report:
              precision    recall  f1-score   support

           0       0.01      0.56      0.01        48
           1       1.00      0.65      0.79     11427

    accuracy                           0.65     11475
   macro avg       0.50      0.60      0.40     11475
weighted avg       0.99      0.65      0.78     11475


ROC AUC Score:
0.6049132536973834


In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import pandas as pd
import numpy as np

# Assuming df3 is your DataFrame
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Set up Stratified K-Fold cross-validation
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Lists to collect metrics for each fold
conf_matrices = []
classification_reports = []
roc_aucs = []

for fold, (train_index, test_index) in enumerate(skf.split(X_scaled, y)):
    print(f"Fold {fold + 1}")

    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    kmeans = KMeans(n_clusters=2, random_state=42)
    kmeans.fit(X_train)

    # Predict cluster labels for test set
    clusters_test = kmeans.predict(X_test)

    # Map clusters to actual class labels based on training set mapping
    cluster_mapping = pd.crosstab(kmeans.labels_, y_train)
    print("Cluster mapping:\n", cluster_mapping)

    fraud_cluster = cluster_mapping[0].idxmin()  # cluster with fewer class 0 samples = fraud cluster

    y_pred = np.where(clusters_test == fraud_cluster, 1, 0)

    # Evaluate metrics
    cm = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred, zero_division=0)
    roc_auc = roc_auc_score(y_test, y_pred)

    conf_matrices.append(cm)
    classification_reports.append(report)
    roc_aucs.append(roc_auc)

    print("Confusion Matrix:\n", cm)
    print("Classification Report:\n", report)
    print("ROC AUC Score:", roc_auc)
    print("-" * 50)

# Summary of all folds
print("Average ROC AUC:", np.mean(roc_aucs))


Fold 1
Cluster mapping:
 col_0   0     1
row_0          
0       5  3641
1      34  5500
Confusion Matrix:
 [[   8    1]
 [1348  938]]
Classification Report:
               precision    recall  f1-score   support

           0       0.01      0.89      0.01         9
           1       1.00      0.41      0.58      2286

    accuracy                           0.41      2295
   macro avg       0.50      0.65      0.30      2295
weighted avg       1.00      0.41      0.58      2295

ROC AUC Score: 0.6496062992125984
--------------------------------------------------
Fold 2
Cluster mapping:
 col_0   0     1
row_0          
0      14  3039
1      25  6102
Confusion Matrix:
 [[   4    5]
 [1517  769]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.44      0.01         9
           1       0.99      0.34      0.50      2286

    accuracy                           0.34      2295
   macro avg       0.50      0.39      0.25      229

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

import pandas as pd
import numpy as np

# Prepare data
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply KMeans clustering
kmeans = KMeans(n_clusters=2, random_state=42)
cluster_labels = kmeans.fit_predict(X_scaled)

# Add cluster labels to original data
df3['Cluster'] = cluster_labels

# Now use Logistic Regression with cluster label as an additional feature
X_new = df3.drop(columns=['Found_fraud'])
y_new = df3['Found_fraud']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_new, y_new, test_size=0.3, random_state=42, stratify=y_new)

# Train logistic regression
lr = LogisticRegression(class_weight='balanced', max_iter=1000)
lr.fit(X_train, y_train)

# Predictions
y_pred = lr.predict(X_test)
y_prob = lr.predict_proba(X_test)[:, 1]

# Evaluate
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=0))
print("\nROC AUC Score:", roc_auc_score(y_test, y_prob))


Confusion Matrix:
 [[  10    4]
 [ 704 2725]]

Classification Report:
               precision    recall  f1-score   support

           0       0.01      0.71      0.03        14
           1       1.00      0.79      0.89      3429

    accuracy                           0.79      3443
   macro avg       0.51      0.75      0.46      3443
weighted avg       0.99      0.79      0.88      3443


ROC AUC Score: 0.8648085655959672


In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import numpy as np

# Custom Autoencoder transformer for scikit-learn compatibility
class AutoencoderTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, encoding_dim=8, epochs=30, batch_size=32):
        self.encoding_dim = encoding_dim
        self.epochs = epochs
        self.batch_size = batch_size
        self.autoencoder = None
        self.encoder = None

    def fit(self, X, y=None):
        input_dim = X.shape[1]
        input_layer = Input(shape=(input_dim,))
        encoded = Dense(self.encoding_dim, activation='relu')(input_layer)
        decoded = Dense(input_dim, activation='linear')(encoded)

        self.autoencoder = Model(input_layer, decoded)
        self.autoencoder.compile(optimizer='adam', loss='mse')

        self.autoencoder.fit(X, X, epochs=self.epochs, batch_size=self.batch_size, verbose=0)

        # Define encoder separately for transform
        self.encoder = Model(input_layer, encoded)
        return self

    def transform(self, X):
        return self.encoder.predict(X)

# =======================
# Load scaled data
X = df3.drop(columns=['Found_fraud']).values
y = df3['Found_fraud'].values

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)

# =======================
# Logistic Regression Pipeline
pipeline_lr = Pipeline([
    ('autoencoder', AutoencoderTransformer(encoding_dim=8, epochs=50)),
    ('classifier', LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42))
])

# Fit and evaluate
pipeline_lr.fit(X_train, y_train)
y_pred = pipeline_lr.predict(X_test)
y_prob = pipeline_lr.predict_proba(X_test)[:, 1]

print("=== Logistic Regression ===")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, zero_division=0))
print("ROC AUC:", roc_auc_score(y_test, y_prob))

# =======================
# Random Forest Pipeline
pipeline_rf = Pipeline([
    ('autoencoder', AutoencoderTransformer(encoding_dim=8, epochs=50)),
    ('classifier', RandomForestClassifier(class_weight='balanced', random_state=42))
])

pipeline_rf.fit(X_train, y_train)
y_pred_rf = pipeline_rf.predict(X_test)
y_prob_rf = pipeline_rf.predict_proba(X_test)[:, 1]

print("=== Random Forest ===")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf, zero_division=0))
print("ROC AUC:", roc_auc_score(y_test, y_prob_rf))


251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
=== Logistic Regression ===
[[   9    5]
 [1172 2257]]
              precision    recall  f1-score   support

           0       0.01      0.64      0.02        14
           1       1.00      0.66      0.79      3429

    accuracy                           0.66      3443
   macro avg       0.50      0.65      0.40      3443
weighted avg       0.99      0.66      0.79      3443

ROC AUC: 0.6956109652960046
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
=== Random Forest ===
[[   4   10]
 [   1 3428]]
              precision    recall  f1-score   support

           0       0.80      0.29      0.42        14
           1       1.00      1.00      1.00      3429

    accuracy                           1.00      3443
   macro avg       0.90      0.64      0.71      3443
weighted avg       1.00

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

import pandas as pd
import numpy as np

# Prepare data
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply KMeans clustering
kmeans = KMeans(n_clusters=5, random_state=42)
cluster_labels = kmeans.fit_predict(X_scaled)

# Add cluster labels to original data
df3['Cluster'] = cluster_labels

# Prepare final data for classification (now including Cluster column)
X_new = df3.drop(columns=['Found_fraud'])
y_new = df3['Found_fraud']

# Define Logistic Regression model
lr = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

# Define Stratified K-Fold CV
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Cross-validated predictions (class labels)
y_pred = cross_val_predict(lr, X_new, y_new, cv=cv)

# Cross-validated predicted probabailities
y_prob = cross_val_predict(lr, X_new, y_new, cv=cv, method='predict_proba')[:, 1]

# Confusion matrix
cm = confusion_matrix(y_new, y_pred)
tn, fp, fn, tp = cm.ravel()

# Class-wise accuracy
accuracy_class_0 = tn / (tn + fp)
accuracy_class_1 = tp / (tp + fn)

# Print results
print("Confusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_new, y_pred, zero_division=0))
print("\nROC AUC Score:", roc_auc_score(y_new, y_prob))
print(f"\nAccuracy for Class 0: {accuracy_class_0:.4f}")
print(f"Accuracy for Class 1: {accuracy_class_1:.4f}")


Confusion Matrix:
 [[  36   12]
 [2416 9011]]

Classification Report:
               precision    recall  f1-score   support

           0       0.01      0.75      0.03        48
           1       1.00      0.79      0.88     11427

    accuracy                           0.79     11475
   macro avg       0.51      0.77      0.46     11475
weighted avg       0.99      0.79      0.88     11475


ROC AUC Score: 0.8750783961961437

Accuracy for Class 0: 0.7500
Accuracy for Class 1: 0.7886


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
from xgboost import XGBClassifier
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam
import pandas as pd
import numpy as np

# Prepare data
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply KMeans clustering
kmeans = KMeans(n_clusters=5, random_state=42)
cluster_labels = kmeans.fit_predict(X_scaled)

# Add cluster labels as feature
X_clustered = np.concatenate([X_scaled, cluster_labels.reshape(-1, 1)], axis=1)

# Define Autoencoder
input_dim = X_clustered.shape[1]
input_layer = Input(shape=(input_dim,))
encoded = Dense(64, activation='relu')(input_layer)
encoded = Dense(32, activation='relu')(encoded)
bottleneck = Dense(16, activation='relu')(encoded)
decoded = Dense(32, activation='relu')(bottleneck)
decoded = Dense(64, activation='relu')(decoded)
output_layer = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=output_layer)
encoder = Model(inputs=input_layer, outputs=bottleneck)

autoencoder.compile(optimizer=Adam(learning_rate=0.001), loss='mse')

# Train Autoencoder
autoencoder.fit(X_clustered, X_clustered,
                epochs=100,
                batch_size=32,
                shuffle=True,
                validation_split=0.2,
                verbose=1)

# Extract bottleneck embeddings
X_embeddings = encoder.predict(X_clustered)

# Optionally, you can also concatenate original cluster labels or features
# X_final = np.concatenate([X_embeddings, cluster_labels.reshape(-1, 1)], axis=1)
X_final = X_embeddings  # pure embedding or mixed feature

# XGBoost Classifier
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

# Cross-validation predictions
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
y_pred = cross_val_predict(xgb, X_final, y, cv=cv)
y_prob = cross_val_predict(xgb, X_final, y, cv=cv, method='predict_proba')[:, 1]

# Confusion matrix
cm = confusion_matrix(y, y_pred)
tn, fp, fn, tp = cm.ravel()

# Class-wise accuracy
accuracy_class_0 = tn / (tn + fp)
accuracy_class_1 = tp / (tp + fn)

# Results
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y, y_pred, zero_division=0))
print("\nROC AUC Score:", roc_auc_score(y, y_prob))
print(f"\nAccuracy for Class 0: {accuracy_class_0:.4f}")
print(f"Accuracy for Class 1: {accuracy_class_1:.4f}")


Epoch 1/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 0.7195 - val_loss: 0.3227
Epoch 2/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.2512 - val_loss: 0.2208
Epoch 3/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.1810 - val_loss: 0.1621
Epoch 4/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1299 - val_loss: 0.1127
Epoch 5/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1026 - val_loss: 0.0841
Epoch 6/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0800 - val_loss: 0.0678
Epoch 7/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0669 - val_loss: 0.0625
Epoch 8/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0576 - val_loss: 0.0534
Epoch 9/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0527 - val_loss: 0.0521
Epoch 10/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0519 - val_loss: 0.0471
Epoch 11/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0447 - val_loss: 0.0417
Epoch 12/100
287/287 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, precision_recall_curve, auc
from xgboost import XGBClassifier
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

# Prepare data
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud'].values

# Impute missing values
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

# KMeans clustering (optional — if you feel clustering adds value)
kmeans = KMeans(n_clusters=5, random_state=42)
cluster_labels = kmeans.fit_predict(X_scaled)

# Add cluster labels as feature
X_clustered = np.concatenate([X_scaled, cluster_labels.reshape(-1, 1)], axis=1)

# Stratified CV setup
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# For metrics
all_y_true, all_y_pred, all_y_prob = [], [], []

for fold, (train_idx, val_idx) in enumerate(cv.split(X_clustered, y)):
    print(f"\n▶️ Fold {fold+1}")

    # Split data
    X_train, X_val = X_clustered[train_idx], X_clustered[val_idx]
    y_train, y_val = y[train_idx], y[val_idx]

    # Autoencoder definition
    input_dim = X_train.shape[1]
    input_layer = Input(shape=(input_dim,))
    encoded = Dense(64, activation='relu')(input_layer)
    encoded = Dense(32, activation='relu')(encoded)
    bottleneck = Dense(16, activation='relu')(encoded)
    decoded = Dense(32, activation='relu')(bottleneck)
    decoded = Dense(64, activation='relu')(decoded)
    output_layer = Dense(input_dim, activation='linear')(decoded)

    autoencoder = Model(inputs=input_layer, outputs=output_layer)
    encoder = Model(inputs=input_layer, outputs=bottleneck)

    autoencoder.compile(optimizer=Adam(learning_rate=0.001), loss='mse')

    # Train autoencoder on training fold only
    autoencoder.fit(X_train, X_train,
                    epochs=50, batch_size=32, shuffle=True,
                    validation_split=0.2, verbose=0)

    # Transform data through bottleneck
    X_train_embedded = encoder.predict(X_train)
    X_val_embedded = encoder.predict(X_val)

    # XGBoost classifier
    xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
    xgb.fit(X_train_embedded, y_train)

    # Predict on validation fold
    y_val_pred = xgb.predict(X_val_embedded)
    y_val_prob = xgb.predict_proba(X_val_embedded)[:, 1]

    # Collect results
    all_y_true.extend(y_val)
    all_y_pred.extend(y_val_pred)
    all_y_prob.extend(y_val_prob)

# Final metrics after CV
cm = confusion_matrix(all_y_true, all_y_pred)
tn, fp, fn, tp = cm.ravel()

print("\nFinal Confusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(all_y_true, all_y_pred, zero_division=0))
print("\nROC AUC Score:", roc_auc_score(all_y_true, all_y_prob))

# Precision-Recall AUC
precision, recall, _ = precision_recall_curve(all_y_true, all_y_prob)
pr_auc = auc(recall, precision)
print("Precision-Recall AUC:", pr_auc)

# Class-wise accuracy
accuracy_class_0 = tn / (tn + fp)
accuracy_class_1 = tp / (tp + fn)
print(f"\nAccuracy for Class 0: {accuracy_class_0:.4f}")
print(f"Accuracy for Class 1: {accuracy_class_1:.4f}")



▶️ Fold 1
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

▶️ Fold 2
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

▶️ Fold 3
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

▶️ Fold 4
287/287 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

▶️ Fold 5
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

Final Confusion Matrix:
 [[   44     4]
 [    0 11427]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.92      0.96        48
           1       1.00      1.00      1.00     11427

    accuracy                           1.00     11475
   macro avg       1.00      0.96      0.98     11475
weighted avg       1.00      1.00      1.00     11475


ROC AUC Score: 0.9999243385548847
Precision-Recall AUC: 0.9999996820537995

Accuracy for Class 0: 0.9167
Accuracy for Class 1: 1.0000
